import sys
import argparse

import optuna


# Default gameplay parameter values used as reference points for the
# synthetic fallback objective.
DEFAULTS = {
    "pass_speed": 5.0,
    "shoot_speed_threshold": 4.0,
    "enemy_proximity_importance": 0.5,
    "defensive_positioning_weight": 1.0,
    "ball_intercept_speed": 3.0,
}

# Parameter search bounds.
BOUNDS = {
    "pass_speed": (1.0, 8.0),
    "shoot_speed_threshold": (2.0, 6.0),
    "enemy_proximity_importance": (0.0, 1.0),
    "defensive_positioning_weight": (0.0, 2.0),
    "ball_intercept_speed": (1.0, 5.0),
}


def _try_headless_selfplay(params):
    """Attempt to launch a headless self-play simulation and return a
    score.

    Returns *None* when the simulation infrastructure is unavailable so
    the caller can fall back to the synthetic objective.
    """
    try:
        from software.simulation.headless_selfplay import HeadlessSelfPlay
    except ImportError:
        return None

    try:
        sim = HeadlessSelfPlay()
        sim.configure(
            pass_speed=params["pass_speed"],
            shoot_speed_threshold=params["shoot_speed_threshold"],
            enemy_proximity_importance=params["enemy_proximity_importance"],
            defensive_positioning_weight=params["defensive_positioning_weight"],
            ball_intercept_speed=params["ball_intercept_speed"],
        )
        result = sim.run()
        # Higher win-rate is better; Optuna maximises when direction="maximize".
        return result.win_rate
    except Exception:
        return None


def _synthetic_objective(params):
    """Compute negative sum of squared deviations from default values.

    We maximise this (i.e. closer to zero = better), giving Optuna a
    smooth surface for dry-run testing.
    """
    total = 0.0
    for name, default_val in DEFAULTS.items():
        total += (params[name] - default_val) ** 2
    return -total


def make_objective():
    """Return an Optuna-compatible objective function."""

    def objective(trial):
        params = {}
        for name, (lo, hi) in BOUNDS.items():
            params[name] = trial.suggest_float(name, lo, hi)

        # Attempt real simulation first.
        sim_score = _try_headless_selfplay(params)
        if sim_score is not None:
            return sim_score

        return _synthetic_objective(params)

    return objective


def run(n_trials=10):
    """Programmatic entry-point so that ``auto_tune.py`` can import and
    call this tuner directly.

    Returns the completed Optuna study.
    """
    storage = optuna.storages.RDBStorage("sqlite:///gameplay_tuner.db")
    study = optuna.create_study(
        study_name="gameplay_tuning",
        storage=storage,
        direction="maximize",
        load_if_exists=True,
    )

    objective = make_objective()
    study.optimize(objective, n_trials=n_trials)

    print("\n===== Best Trial =====")
    best = study.best_trial
    print(f"  Value (score): {best.value:.6f}")
    print("  Parameters:")
    for key, value in best.params.items():
        print(f"    {key}: {value:.6f}")

    print("\n===== Suggested parameters.proto field changes =====")
    print("// Auto-generated by optuna_gameplay_tuner.py")
    print(f"pass_speed: {best.params['pass_speed']:.4f}")
    print(f"shoot_speed_threshold: {best.params['shoot_speed_threshold']:.4f}")
    print(f"enemy_proximity_importance: {best.params['enemy_proximity_importance']:.4f}")
    print(f"defensive_positioning_weight: {best.params['defensive_positioning_weight']:.4f}")
    print(f"ball_intercept_speed: {best.params['ball_intercept_speed']:.4f}")

    return study


def main():
    parser = argparse.ArgumentParser(
        description="Optuna-based gameplay parameter tuner for sim-to-real transfer"
    )
    parser.add_argument(
        "--n_trials",
        type=int,
        default=10,
        help="Number of Optuna trials to run (default: 10)",
    )
    args = parser.parse_args()

    run(n_trials=args.n_trials)


if __name__ == "__main__":
    main()
