import os
import sys
import argparse

import optuna


# Default physics parameter values used as reference points for the
# synthetic fallback objective.
DEFAULTS = {
    "robot_mass": 2.5,
    "wheel_radius": 0.05,
    "front_wheel_angle_deg": 45.0,
    "back_wheel_angle_deg": 120.0,
    "friction_coefficient": 0.5,
}

# Parameter search bounds.
BOUNDS = {
    "robot_mass": (0.5, 5.0),
    "wheel_radius": (0.01, 0.1),
    "front_wheel_angle_deg": (30.0, 60.0),
    "back_wheel_angle_deg": (100.0, 150.0),
    "friction_coefficient": (0.1, 1.0),
}


def _load_kinematics_stats(logs_dir):
    """Try to load kinematics CSVs from *logs_dir* and return summary stats.

    Returns a dict of trajectory statistics if data is available, or an
    empty dict if the files do not exist or pandas is not available.
    """
    stats = {}
    try:
        import pandas as pd
    except ImportError:
        return stats

    world_csv = os.path.join(logs_dir, "kinematics_world.csv")
    if os.path.isfile(world_csv):
        df = pd.read_csv(world_csv)
        if not df.empty and "ball_x" in df.columns and "ball_y" in df.columns:
            stats["ball_x_mean"] = float(df["ball_x"].mean())
            stats["ball_y_mean"] = float(df["ball_y"].mean())
            stats["ball_x_std"] = float(df["ball_x"].std())
            stats["ball_y_std"] = float(df["ball_y"].std())
            stats["n_world_rows"] = len(df)
    return stats


def _try_erforce_objective(params):
    """Attempt to run the ErForce simulator and return a loss value.

    Returns *None* when the simulator is unavailable so the caller can
    fall back to the synthetic objective.
    """
    try:
        from software.simulation.er_force_simulator import ErForceSimulator
    except ImportError:
        return None

    try:
        simulator = ErForceSimulator()
        simulator.set_physics(
            robot_mass=params["robot_mass"],
            wheel_radius=params["wheel_radius"],
            front_wheel_angle_deg=params["front_wheel_angle_deg"],
            back_wheel_angle_deg=params["back_wheel_angle_deg"],
            friction_coefficient=params["friction_coefficient"],
        )
        result = simulator.run()
        return result.tracking_error
    except Exception:
        return None


def _synthetic_objective(params):
    """Compute sum of squared deviations from default parameter values.

    This gives Optuna a smooth, well-behaved objective surface for
    dry-run / testing purposes where the real simulator is unavailable.
    """
    total = 0.0
    for name, default_val in DEFAULTS.items():
        total += (params[name] - default_val) ** 2
    return total


def make_objective(logs_dir):
    """Return an Optuna-compatible objective function."""

    # Pre-load kinematics stats once (shared across trials).
    kinematics_stats = _load_kinematics_stats(logs_dir)

    def objective(trial):
        params = {}
        for name, (lo, hi) in BOUNDS.items():
            params[name] = trial.suggest_float(name, lo, hi)

        # Attempt real simulation first.
        sim_loss = _try_erforce_objective(params)
        if sim_loss is not None:
            loss = sim_loss
        else:
            loss = _synthetic_objective(params)

        # Incorporate kinematics data if available: add a small
        # regularisation term based on how far the ball spread is from
        # the suggested friction coefficient.
        if kinematics_stats:
            spread = kinematics_stats.get("ball_x_std", 0.0) + kinematics_stats.get("ball_y_std", 0.0)
            loss += 0.01 * abs(spread - params["friction_coefficient"])

        return loss

    return objective


def run(logs_dir=".", n_trials=10):
    """Programmatic entry-point so that ``auto_tune.py`` can import and
    call this tuner directly.

    Returns the completed Optuna study.
    """
    storage = optuna.storages.RDBStorage("sqlite:///physics_tuner.db")
    study = optuna.create_study(
        study_name="physics_tuning",
        storage=storage,
        direction="minimize",
        load_if_exists=True,
    )

    objective = make_objective(logs_dir)
    study.optimize(objective, n_trials=n_trials)

    print("\n===== Best Trial =====")
    best = study.best_trial
    print(f"  Value (loss): {best.value:.6f}")
    print("  Parameters:")
    for key, value in best.params.items():
        print(f"    {key}: {value:.6f}")

    print("\n===== Suggested robot_constants.h changes =====")
    print("// Auto-generated by optuna_physics_tuner.py")
    print(f"constexpr double ROBOT_MASS_KG = {best.params['robot_mass']:.4f};")
    print(f"constexpr double WHEEL_RADIUS_M = {best.params['wheel_radius']:.6f};")
    print(f"constexpr double FRONT_WHEEL_ANGLE_DEG = {best.params['front_wheel_angle_deg']:.2f};")
    print(f"constexpr double BACK_WHEEL_ANGLE_DEG = {best.params['back_wheel_angle_deg']:.2f};")
    print(f"constexpr double FRICTION_COEFFICIENT = {best.params['friction_coefficient']:.4f};")

    return study


def main():
    parser = argparse.ArgumentParser(
        description="Optuna-based physics parameter tuner for sim-to-real transfer"
    )
    parser.add_argument(
        "--logs_dir",
        type=str,
        default=".",
        help="Directory containing kinematics CSV logs (default: '.')",
    )
    parser.add_argument(
        "--n_trials",
        type=int,
        default=10,
        help="Number of Optuna trials to run (default: 10)",
    )
    args = parser.parse_args()

    run(logs_dir=args.logs_dir, n_trials=args.n_trials)


if __name__ == "__main__":
    main()
