---

- name: Remote flashing
  hosts: THUNDERBOTS_HOSTS
  vars:
    all_services:
      - thunderloop
    all_actions:
      - stop
      - sync
      - start
    binary_paths:
      thunderloop: ../../thunderloop_main
    zip_paths:
      diagnostics: ../../robot_diagnostics_cli/robot_diagnostics_cli_tar.tar
#      // ADD SOMETHINGS HERE

  tasks:

    - debug:
        msg: "[Robot ID = {{ inventory_hostname }}]"
      tags: always

    - name: Extract services & actions from tags
      set_fact:
        services: "{{ all_services if ansible_run_tags | intersect(all_services)|length == 0 else ansible_run_tags | intersect(all_services) }}"
        actions: "{{ all_actions if ansible_run_tags|intersect(all_actions)|length == 0 else ansible_run_tags | intersect(all_actions)}}"
      tags: always

    - debug:
        msg: "Performing the following actions: {{ actions }}
        on the following services: {{ services }}"
      tags: always

    - name: Start Flash Process
      block:
        - name: Stop Services
          become: true
          become_method: sudo
          ansible.builtin.systemd:
            name: "{{ service_name }}"
            masked: no
            daemon_reload: yes
            state: stopped
          with_items: "{{ services }}"
          loop_control:
            loop_var: service_name
          when: "'stop' in actions"
          tags: always

        - name: Delete everything on ~/
          file:
            state: absent
            path: /home/robot/thunderbots_binaries
          become_method: sudo
          become: true
          register: result

        - name: Sync Binaries
          ansible.posix.synchronize:
            src: "{{ binary_paths[service_name] }}"
            dest: ~/thunderbots_binaries/
            recursive: yes
            copy_links: yes
          with_items: "{{ services }}"
          loop_control:
            loop_var: service_name
          when: "'sync' in actions"
          tags: always

        - name: Sync Zipped Binaries
          with_items: "{{ zip_paths }}"
          loop_control:
            loop_var: zip_name
          ansible.posix.synchronize:
            src: "{{ zip_paths[zip_name] }}"
            dest: ~/thunderbots_binaries/
            recursive: yes
            copy_links: yes
          tags: always

        - name: Unzipping Binaries
          command: 'tar xopf ~/thunderbots_binaries/*.tar'
          args:
            chdir: ~/thunderbots_binaries

#        - name: Create symbolic link to diagnostics CLI
#          file:
#            src: /home/robot/thunderbots_binaries/robot_diagnostics_cli/robot_diagnostics_cli
#            dest: /home/robot/tbots
#            state: link
#            force: yes

        - name: Start Services
          become: true
          become_method: sudo
          ansible.builtin.systemd:
            name: "{{ service_name }}"
            masked: no
            daemon_reload: yes
            state: started
          with_items: "{{ services }}"
          loop_control:
            loop_var: service_name
          when: "'start' in actions"
          tags: always
